[package]
name = "flutter_asset_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
yaml-rust = "0.4.5"
anyhow = "1.0.86"
iced = "0.12.1"
iced_aw = { version = "0.9.3", default-features = false, features = ["icons"] }
